<form action="addBookForm" method="POST">
    <label for="titleName">Ajout d'un titre</label><br>
    <input type="text" name="titleName" id="titleName"/><br>
    
    
      <label for="msg">Votre message</label><br>
      <textarea id="msg" maxlength="300" name="msg " cols="30 " rows="8 " placeholder="Votre message ici "></textarea><br>
          
        <label for="img">ajout d'une image ou photo</label><br>
        <input type="file" id="img" name="img" accept="image/png, image/jpeg" /><br>
        
       <input type="submit" name="" value="ajout d'article"/> 
</form>