    <footer>
        
        
        <div class="footer">
            <div> 
                <h4> A propos</h4>
                 <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook "> </i></a>
                 <a href="https://entreprendre.service-public.fr/vosdroits/F33527" target="_blank">cgu</a>
                 <a href="https://entreprendre.service-public.fr/vosdroits/F31228#:~:text=Les%20mentions%20l%C3%A9gales%20sont%20les,ou%20dans%20une%20page%20d%C3%A9di%C3%A9e." target="_blank">mention legal</a>
                 
            </div>
            <div>
                <img src="./assets/img/drapeaux.png" alt="logo site Djue Koffi">
            </div>
            <div>
                <a href="<?=$base_uri[0] ?>/public/contact">contact</a>
                 <a href="<?=$base_uri[0] ?>/public/shop">shop</a>
                
            </div>
            
       </div>
        <div class="mention">
            <small>product by jibeyyy</small>
        </div>
    </footer>
<script src="./assets/js/index.js"></script>

</body>

</html>