    <footer>
        <div class="footer">
            <a href="https://www.facebook.com/"><i class="fab fa-facebook "> </i></a>
            <a href="https://entreprendre.service-public.fr/vosdroits/F33527">cgu</a>
            <a href="https://entreprendre.service-public.fr/vosdroits/F31228#:~:text=Les%20mentions%20l%C3%A9gales%20sont%20les,ou%20dans%20une%20page%20d%C3%A9di%C3%A9e.">mention legal</a>
            <a href="<?=$base_uri[0] ?>/public/contact">contact</a>
            <a href="<?=$base_uri[0] ?>/public/shop">shop</a>
        </div>
        <div class="mention">
            <small>product by jibeyyy</small>
        </div>
    </footer>
<script src="./assets/js/index.js"></script>

</body>

</html>