<!doctype html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="2 phrase maxi ou 160 charactere">

    <title>site officiel DJUE Koffi Mathieu </title>

    <link rel="icon" type="image/png" href="./assets/img/drapeaux.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <link rel="stylesheet" href="normalize.css" type="text/css" />
    <link rel="stylesheet" href="./assets/css/style.css" type="text/css">
</head>

<body>
    <header class="header">
        <img src="./assets/img/drapeaux.png" alt="logo site Djue Koffi" width="50" height="60">
        <nav>
            <ul>
                <li><a href="<?=$base_uri[0] ?>/public/home">Accueil</a></li>
                <li><a href="<?=$base_uri[0] ?>/public/shop">shop</a></li>
                <li><a href="<?=$base_uri[0] ?>/public/contact">contact</a></li>
                <li><a href="<?=$base_uri[0] ?>/public/login">connexion</a></li>
                <li><a href="<?=$base_uri[0] ?>/public/register">créé compte</a></li>
            </ul>
            
        </nav>
       
    </header>
