<main>

        <h1>Bienvenue sur ton site Mathieu </h1>

        <h2>Gérer la Boutique</h2>
        

       <table>
        <thead>
             <tr>
                <th>Titre</th>
                <th>Image</th>
                <th>Description</th>
                <th>Prix</th>
                <th>suprimer</th>
                <th>Mettre a jour</th>
             </tr>
       </thead>
        <tbody>
            <tr>
                <td id="nameBook">Agniassou</td>
                <td id="imgBook"><img src="./assets/img/bou.jpg" width="100" height="100"></td>
                <td id="resumeBook">resume du livre</td><!-- echo $Books['resume'];-->
                <td id="priceBook">17€</td>
                <td><input type="submit" name="deleteBook" value="Suprimer"></td>
                <td><a href="<?=$base_uri[0] ?>/public/admin/add">Mettre à jour</a></td>
                
            </tr>
             <tr>
                <td id="nameBook">Agniassou</td>
                <td id="imgBook"><img src="./assets/img/bou.jpg" width="100" height="100"></td>
                <td id="resumeBook">resume du livre</td><!-- echo $Books['resume'];-->
                <td id="priceBook">17€</td>
                <td><input type="submit" name="deleteBook" value="Suprimer"></td>
                <td><a href="<?=$base_uri[0] ?>/public/admin/add">Mettre à jour</a></td>
                
            </tr>
             <tr>
                <td id="nameBook">Agniassou</td>
                <td id="imgBook"><img src="./assets/img/bou.jpg" width="100" height="100"></td>
                <td id="resumeBook">resume du livre</td><!-- echo $Books['resume'];-->
                <td id="priceBook">17€</td>
                <td><input type="submit" name="deleteBook" value="Suprimer"></td>
                <td><a href="<?=$base_uri[0] ?>/public/admin/add">Mettre à jour</a></td>
               
            </tr>
             <tr>
                <td id="nameBook">Agniassou</td>
                <td id="imgBook"><img src="./assets/img/bou.jpg" width="100" height="100"></td>
                <td id="resumeBook">resume du livre</td><!-- echo $Books['resume'];-->
                <td id="priceBook">17€</td>
                <td><input type="submit" name="deleteBook" value="Suprimer"></td>
                <td><a href="<?=$base_uri[0] ?>/public/admin/add">Mettre à jour</a></td>
              
            </tr>
       </tbody>
      </table>

    </main>
