
<main class="mainAdmin">
    <section>
         <h1>Bienvenue sur ton site Mathieu</h1>
         <h2>Gérer la Boutique</h2>
   
       <div class="adminTable">
            <table class⁼"presentTableAdmin">

                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Photo Livre</th>
                        <th>Prix</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data['books'] as $key => $book) : ?>
                
                <tr>
                    <td><?= $book->getName()?></td>
                    <td><img class="imgAdmin" src="<?php echo  $base_uri[0].'/public/assets/img/'.$book->getImg(); ?>" alt="image livre Djue Koffi" width="50" height="50"</td>
                    <td><?= $book->getPrice() ?>€</td>
                    <td>
                        <form method="post">
                            <input type="hidden" value="<?= $book->getId() ?>" name="bookid"/>
                            <input type="submit" name="deleteBook" aria-label="suprimer article" value="Supprimer">
                        </form>
                    </td>
                    <td><a href="<?= $base_uri[0]; ?>/public/update?id=<?= $book->getId(); ?>">Mettre à jour</a></td>
                     
                </tbody>
            <?php endforeach; ?>
            </table>
            </div>
       </tbody>
      </table>
       </section>
      <section class="sectionCreate">
            <h2>Ajouter un livre</h2>
               <div class="divCreate">
                  <form class="formCreate" method="POST">
                      <div>
                          <label for="name">Ajout d'un titre</label><br>
                          <input type="text" name="name" id="name"><br>
                     
                           <label for="img">ajout d'une image ou photo</label><br>
                           <input class="inputForm" type="file" id="img" name="img" accept="image/png, image/jpeg"><br>
                      </div>
                      <div>                
                           <label for="resume">la description</label><br>
                           <textarea id="resume" maxlength="300" name="resume" cols="30 " rows="8 " placeholder="déscription ici "></textarea><br>
                     </div>
                     <div>
                            <label for="price">Ajout d'un prix</label><br>
                                                <input type="number" name="price" id="price"><br>
                    </div>
                    <div>
                            <input type="submit" name="insertBook" value="créé article"> 
                    </div>
                 </form>
             </div>
    </section>
</main>