
<main class="mainAdmin">
 
        <h1>Bienvenue sur ton site Mathieu </h1>

        <h2>Gérer la Boutique</h2>
       <div class="adminTable">
            <table class⁼"presentTableAdmin">

                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Photo Livre</th>
                        <th>Prix</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data['books'] as $key => $book) : ?>
                
                <tr>
                    <td><?= $book->getName()?></td>
                    <td><img class="imgAdmin" src="<?php echo  $base_uri[0].'/public/assets/img/'.$book->getImg(); ?>" alt="image livre Djue Koffi" width="50" height="50"</td>
                    <td><?= $book->getPrice() ?>€</td>
                    <td>
                        <form method="post">
                            <input type="hidden" value="<?= $book->getId() ?>" name="bookid"/>
                            <input type="submit" name="deleteBook" value="Supprimer">
                        </form>
                    </td>
                    <td><a href="<?= $base_uri[0] ?>/public/admin/update">Mettre à jour</a></td>
                </tr>
                </tbody>
            <?php endforeach; ?>
            </table>
            </div>
       </tbody>
      </table>
    </main>