<form action="" method="POST">
    <label for="name">Ajout d'un titre</label><br>
    <input type="text" name="name" id="name"/><br>
    
     <label for="img">ajout d'une image ou photo</label><br>
        <input type="file" id="img" name="img" accept="image/png, image/jpeg" /><br>
    
      <label for="resume">la description</label><br>
      <textarea id="resume" maxlength="300" name="resume" cols="30 " rows="8 " placeholder="déscription ici "></textarea><br>

       <input type="submit" name="addNewForm" value="Mettre à jour/créé article"/> 
</form>

<div class="contenair">
 <div class="itemNew">
 <div class="titleNew">titre</div>
 <div class="resumeNew">description</div>
 </div>
 <div class="imgNew">image falcutatif</div>
</div>