<form method="POST">
    <label for="name">Ajout d'un titre</label><br>
    <input type="text" name="name" id="name"/><br>
    
     <label for="img">ajout d'une image ou photo</label><br>
        <input type="file" id="img" name="img" accept="image/png, image/jpeg" /><br>
    
      <label for="resume">la description</label><br>
      <textarea id="resume" maxlength="300" name="resume" cols="30 " rows="8 " placeholder="déscription ici "></textarea><br>
          
       <label for="price">Ajout d'un prix</label><br>
    <input type="number" name="price" id="price"/><br>
           <label for="stock">Ajout d'un stock</label><br>
    <input type="number" name="stock" id="stock"/><br>
        
       <input type="submit" name="updateBook" value="modifié l'article"/> 
</form>