<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>page administrateur</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <link rel="icon" type="image/svg+xml" href="./assets/img/drapeaux.png">

    <link rel="stylesheet" href="./assets/css/style.css">
 
</head>

<body>
    <header>
    <nav>
        <ul>
            <li><a href="<?=$base_uri[0] ?>/public/admin">gérer la boutique</a></li>
            <li><a href="<?=$base_uri[0] ?>/public/admin/add">créé article</a></li>
            
        </ul>
    </nav>
  </header>