  <main class="mainContact">
        
            <h1>Formulaire de Contact</h1>
                <p>Pour tous renseignements, veuillez utiliser le formulaire de contact</p>
       
        <section>

            <form class="ContactForm" method="post">
                <fieldset>
                    <legend> Me contacter</legend>

                    <label for="lastName">Votre Nom</label><br>
                    <input type="text" name="lastName" id="lastName" required pattern="^[A-Za-z '-]=$" maxlength="25"><br>

                    <label for="firstName">Votre prénom</label><br>
                    <input type="text" name="firstName " id="firstName" required pattern="^[A-Za-z '-]+$"><br>

                    <label for="email">votre Mail</label><br>
                    <input type="email" name="email " id="email" required pattern="^[A-Za-z]+@{1}[A-Za-z]+\.{1}[A-Za-z]{2,}$"><br>

                    <label for="msg">Votre message</label><br>
                    <textarea id="msg" maxlength="300" name="msg" cols="30" rows="8" placeholder="Votre message ici"></textarea><br>

                    <input type="submit" name="btnForm" value="Envoyer">
                </fieldset>
            </form>
        </section>
        <section class="coord">
                <h2>Coordonnées et plan d'accès</h2>
            <div class="iframe">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d86818.9267528468!2d-1.9977501201247532!3d47.15606310713471!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4805a02a10cc5f6d%3A0xe05c9ec85981116d!2sChaumes-en-Retz!5e0!3m2!1sfr!2sfr!4v1692351828361!5m2!1sfr!2sfr"
                    width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div class="divList">
                <ul>
                        <li class="listMap">
                            <i class="fas fa-map-marked"></i>
                            <div class="divAdress">
                                <address title="adresse Mr Djue Koffi Mathieu">Rue de Bourgneuf <br>
                                  44320 Chaumes en Retz</address>
                             </div>
                        </li>
                        <li>
                            <i class="fas fa-phone"></i><a href="tel:+33386472612">03 86 47 26 12</a>
                        </li>
                    </ul>
            </div>
        </section>
         <section>
            <div class="titleSelect">
                 <h3>Vous recherchez un élément?</h3>
                 <p>Voci un selecteur de page pour mieux vous retrouvez à tout de suite dans les prochaines pages </p>
            </div>
             <div class="select">
            <label for="selecteur"></label>
            <select id="selecteur" onchange="nextPage()">
                <optgroup label="Sélectionnez une page :">
                    <option>Sélectionnez un onglet :</option>
        <option value="<?=$base_uri[0] ?>/public/home">Accueil du site</option>
        <option value="<?=$base_uri[0] ?>/public/home">A propos de l'Auteur</option>
        <option value="<?=$base_uri[0] ?>/public/home">Photos</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Boutique</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Panier</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Formulaire de Contact</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Coordonnées</option>
        <option value="<?=$base_uri[0] ?>/public/login">Connexion</option>
        <option value="<?=$base_uri[0] ?>/public/user">Mon compte</option>
        <option value="<?=$base_uri[0] ?>/public/register">Créer compte</option>
       </optgroup>
    </select>
        </div>
        </section>
    </main>