  <main>
        
            <img class="logoContact" src="./assets/img/machine.jpg" alt="logo manuscrit" width="80px" height="80">
            <h1>Formulaire de Contact</h2>
                <img class="logoContact" src="./assets/img/machine.jpg" alt="logo manuscrit" width="80px" height="80">
                <p class=".paraTitle">Pour tous renseignements, veuillez utiliser le formulaire de contact</p>
       
        <section class="">

            <form class="ContactForm" action="" method="POST">
                <fieldset>
                    <legend> Me contacter</legend>

                    <label for="lastName">Votre Nom</label><br>
                    <input type="text" name="lastName" id="lastName" required pattern="^[A-Za-z '-]=$" maxlength="25" /><br>

                    <label for="firstName ">Votre prénom</label><br>
                    <input type="text" name="firstName " id="firstName " required pattern="^[A-Za-z '-]+$" /><br>

                    <label for="email" required>votre Mail</label><br>
                    <input type="mail" name="mail " id="mail " required pattern="^[A-Za-z]+@{1}[A-Za-z]+\.{1}[A-Za-z]{2,}$" /><br>

                    <label for="msg">Votre message</label><br>
                    <textarea id="msg" maxlength="300" name="msg " cols="30 " rows="8 " placeholder="Votre message ici " required pattern="^[A-Za-z]+@{1}[A-Za-z]+\.{1}[A-Za-z]{2,}$" required pattern="[A-Za-z '-\(\)@0123456789,;]+$"></textarea><br>

                    <input type="submit" name="btnForm" value="Envoyer">
                </fieldset>
            </form>
        </section>
        <section class="coord">
            <div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d86818.9267528468!2d-1.9977501201247532!3d47.15606310713471!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4805a02a10cc5f6d%3A0xe05c9ec85981116d!2sChaumes-en-Retz!5e0!3m2!1sfr!2sfr!4v1692351828361!5m2!1sfr!2sfr"
                    width="300" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div>
                <span>
                <i class="fas fa-map-marked"></i>
                <address title="adresse Mr Djue Koffi Mathieu" style="cursor:default;">Rue de Bourgneuf </br>
                44320 Chaumes en Retz</address>
                </span>
                <span>
                    <i class="fas fa-phone"></i>
                    <a href="tel:+33000000000">00 00 00 00 00</a>
                </span>
            </div>
        </section>
    </main>