<main class="mainRegister">
          <h1>Réinitialisation du mot de passe</h1>
          <p>Une fois votre e-mail renseigné et validé, vous recevrez un e-mail avec la procédure pour changer votre mot de passe. Si vous avez perdu votre identifiant et que vous souhaitez le récupérer, retrouvez-le dans les premiers e-mails de contact ou envoyez une demande via le formulaire de <a href="<?=$base_uri[0] ?>/public/contact">contact.</a>
          </p>
    
    <form class="form" method="POST">
        
        <label for="email">Votre Email : </label> <br>
        
        <input type="email" name="email" id="email" required pattern="^[A-Za-z]+@{1}[A-Za-z]+\.{1}[A-Za-z]{2,}$" placeholder="@email"><br>

        <input class="btnInput" type="submit" name="InitialBtn" value="Réinitialiser le mot de passe">
    
    </form>
   
      <section>
            <div class="titleSelect">
                 <h3>Vous recherchez un élément?</h3>
                 <p>Voici un selecteur de page pour mieux vous retrouvez à tout de suite dans les prochaines pages </p>
            </div>
             <div class="select">
            <label for="selecteur"></label>
            <select id="selecteur" onchange="nextPage()">
                <optgroup label="Sélectionnez une page :">
                    <option>Sélectionnez un onglet :</option>
        <option value="<?=$base_uri[0] ?>/public/home">Accueil du site</option>
        <option value="<?=$base_uri[0] ?>/public/home">A propos de l'Auteur</option>
        <option value="<?=$base_uri[0] ?>/public/home">Photos</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Boutique</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Panier</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Formulaire de Contact</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Coordonnées</option>
        <option value="<?=$base_uri[0] ?>/public/login">Connexion</option>
        <option value="<?=$base_uri[0] ?>/public/user">Mon compte</option>
        <option value="<?=$base_uri[0] ?>/public/register">Créer compte</option>
       </optgroup>
    </select>
        </div>
        </section>

</main>