   <main>
          <h1>Réinitialisation du mot de passe</h1>
    
    
    <form class="form" action="reset_password.php" method="POST">
        
        <label for="email">Votre Email : </label> </br>
        
        <input type="email" name="email" id="email" required pattern="^[A-Za-z]+@{1}[A-Za-z]+\.{1}[A-Za-z]{2,}$" placeholder="@email" required /></br>

        <input class="btnInput" type="submit" name="InitialBtn" value="Réinitialiser le mot de passe"/>
    
    </form>
   
    <div class="infoConnect">
            <a class="small" href="<?=$base_uri[0] ?>/public/home">Accueil</a>
        </div>

</main>