 <main>
        <h1>Bienvenue sur la boutique Officiel</h1>
        <section class="avatar">
            <figure>
                <img src="./assets/img/personal.jpg" alt="Mr DJUE Koffi Mathieu" width="300" height="350">
                <figcaption>DJUE Koffi Mathieu - Auteur - Aide-soignant</figcaption>
            </figure>

        </section>
        <section>
            <article class="about" id="about">
                <div>
                    <img src="./assets/img/avatar.jpg" alt="portrait de Mr Djue Koffi Mathieu" width="300" height="300">
                </div>
                <div>
                    <h2>A propos de l'Auteur</h2>
                    <p>quelque chose a écrire</p>
                </div>
            </article>
            
        </section>
        <section class="news">
            
            <div class="contenair">
 <div class="itemNew">
 <div class="titleNew">titre</div>
 <div class="resumeNew">description</div>
 </div>
 <div class="imgNew">image falcutatif</div>
</div>
        </section>
        <section class="carousel">
            <p>Voici des photos illustrant certain passage des livres</p>
            <div class="slider">

                <a href="#slide-1">1</a>
                <a href="#slide-2">2</a>
                <a href="#slide-3">3</a>
                <a href="#slide-4">4</a>
                <a href="#slide-5">5</a>

                <div class="slides">
                    <div id="slide-1">
                        <img src="" alt="">
                    </div>
                    <div id="slide-2">
                        <img src="" alt="">
                    </div>
                    <div id="slide-3">
                        <img src="" alt="">
                    </div>
                    <div id="slide-4">
                        <img src="" alt="">
                    </div>
                    <div id="slide-5">
                        <img src="" alt="">
                    </div>
                </div>
            </div>

        </section>
    </main>