 <main>
       
        <section class="avatar">
             <h1>Bienvenue sur la boutique Officiel</h1>
            <figure>
                <img src="./assets/img/personal.jpg" alt="Mr DJUE Koffi Mathieu" width="300" height="350">
                <figcaption>DJUE Koffi Mathieu - Auteur - Aide-soignant</figcaption>
            </figure>

        </section>
        <section>
            <article class="about" id="about">
                <div class="aboutImg">
                    <img class="aboutImg" src="./assets/img/avatar.jpg" alt="portrait de Mr Djue Koffi Mathieu" width="300" height="300">
                </div>
                <div class="aboutText">
                    <h2 class="aboutTitle">A propos de l'Auteur</h2>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                    sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                    magna aliquam erat volutpat.</p>
                    
                    <p>Ut wisi enim ad minim veniam,
                    quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                    ut aliquip ex ea commodo consequat. Duis autem vel eum iriure
                    dolor in hendrerit in vulputate velit esse molestie consequat,
                    vel illum dolore eu feugiat nulla facilisis at vero eros et
                    accumsan et iusto odio dignissim qui blandit praesent luptatum
                    zzril delenit augue duis dolore te feugait nulla facilisi.</p>
                    <p>
                    Nam liber tempor cum soluta nobis eleifend option congue
                    nihil imperdiet doming id quod mazim placerat facer possim
                    assum. Typi non habent claritatem insitam; est usus legentis
                    in iis qui facit eorum claritatem. Investigationes
                    demonstraverunt lectores legere me lius quod ii legunt saepius.
                    Claritas est etiam processus dynamicus, qui sequitur mutationem
                    consuetudium lectorum. Mirum est notare quam littera gothica,
                    quam nunc putamus parum claram, anteposuerit litterarum formas
                    humanitatis per seacula quarta decima et quinta decima. Eodem
                    modo typi, qui nunc nobis videntur parum clari, fiant sollemnes
                    in futurum.</p>
                </div>
            </article>
            

        <section class="carousel">
            <p>Voici des photos illustrant certain passage des livres</p>
            <div class="carousel-container">
    <div class="carousel">
        <div class="carousel-item">
            <img src="./assets/img/imagecar1.jpg" alt="village cote d'ivoir">
        </div>
        <div class="carousel-item">
            <img src="./assets/img/imagecar2.jpg" alt="route cote d'ivoir">
        </div>
        <div class="carousel-item">
            <img src="./assets/img/imagecar3.jpg" alt="cacaoyer cote d'ivoir">
        </div>
    </div>
    <button class="prev-btn">&#8249;</button>
    <button class="next-btn">&#8250;</button>
</div>

        </section>
    </main>