 <main>
        <h1> Bienvenue sur la page de connexion</h1>

        <form class="form" method="POST">
            <fieldset>
                <legend>Connexion a votre compte</legend>
                <label for="email">Votre identifiant :</label><br>
                <input type="email" id="email" name="email" aria-label="Adresse email" required pattern="^[A-Za-z]+@[A-Za-z]+\.[A-Za-z]{2,}$" placeholder="Votre adresse email"><br>

                <label for="password">Votre mot de passe : </label><br>
                <input type="password" name="password" id="password" placeholder="Votre Mot de passe" required><br>

                <input class="btnInput" type="submit" name="loginForm" value="Login">
            </fieldset>
        </form>
        <hr>
        <div class="infoConnect">
        <div>
           <a class="small" href="<?=$base_uri[0] ?>/public/forgot-password">mot de pass oublié ?</a>
        </div>
        <div>
            <a class="small" href="<?=$base_uri[0] ?>/public/register">créé compte</a>
        </div>
        </div>
         <section>
            <div class="titleSelect">
                 <h3>Vous recherchez un élément?</h3>
                 <p>Voci un selecteur de page pour mieux vous retrouvez à tout de suite dans les prochaines pages </p>
            </div>
             <div class="select">
            <label for="selecteur"></label>
            <select id="selecteur" onchange="nextPage()">
                <optgroup label="Sélectionnez une page :">
                    <option>Sélectionnez un onglet :</option>
        <option value="<?=$base_uri[0] ?>/public/home">Accueil du site</option>
        <option value="<?=$base_uri[0] ?>/public/home">A propos de l'Auteur</option>
        <option value="<?=$base_uri[0] ?>/public/home">Photos</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Boutique</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Panier</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Formulaire de Contact</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Coordonnées</option>
        <option value="<?=$base_uri[0] ?>/public/login">Connexion</option>
        <option value="<?=$base_uri[0] ?>/public/user">Mon compte</option>
        <option value="<?=$base_uri[0] ?>/public/register">Créer compte</option>
       </optgroup>
    </select>
        </div>
        </section>
    </main>