
<main class="mainShop">
    <h1> La Boutique</h1>
    <p class="paraTitle">voici la liste des livres en vente </p> 
    <div class="listBook">
            
            <div class="book">
                <?php foreach($data as $book):?>
                <div class="nameBook">
                    <h3><?= $book->getName(); ?></h3>
                </div>
                    <div class="bookImg">
                        <img class="imgCart" src="<?php echo  $base_uri[0].'/public/assets/img/'.$book->getImg(); ?>" alt="image livre Djue Koffi" width="200" height="250">
                    </div>
                    <div class="bookDescrip">
                        <?= $book->getResume(); ?>
                    </div>
                    <div class="basketBook">
                         <form class="itemForm" method="POST">
                        <p>Prix : <?php echo $book->getPrice(); ?> €</p>
                        <small>Frais de port: 7€</small><br>
                           
                            <label>Quantité :</label><br>
                            
                            <input type="number" name="quantity" min="1" max="9" value="1"><br>
                            <input type="submit" name="paner" value="Ajouter au panier">
                        </form>
                    </div>
                   
                    <?php endforeach;?>
                </div>
            </div>

    <img class="imgShop" src="./assets/img/separate.png" alt="deco séparateur">
    <section class="sectionPaner">

       
        <h2>Mon panier</h2>
        <table class="tablePaner">
            <thead>
                 <tr>
                     <th>Livres</th>
                     <th>Quantité</th>
                     <th>Prix €</th>
                     <th>Total</th>
                 </tr>
            </thead>
            <tbody>
                 <tr>
                    <td>livre</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                 </tr>
            </tbody>
        </table>
         
        <input class="btnPaner" type="submit" name="valiateBtn" value="Valider le panier">

    </section>
    <img class="imgShop" src="./assets/img/separate.png" alt="deco séparateur">
     <section>
            <div class="titleSelect">
                 <h3>Vous recherchez un élément?</h3>
                 <p>Voci un selecteur de page pour mieux vous retrouvez à tout de suite dans les prochaines pages </p>
            </div>
             <div class="select">
            <label for="selecteur"></label>
            <select id="selecteur" onchange="nextPage()">
                <optgroup label="Sélectionnez une page :">
                    <option>Sélectionnez un onglet :</option>
        <option value="<?=$base_uri[0] ?>/public/home">Accueil du site</option>
        <option value="<?=$base_uri[0] ?>/public/home">A propos de l'Auteur</option>
        <option value="<?=$base_uri[0] ?>/public/home">Photos</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Boutique</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Panier</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Formulaire de Contact</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Coordonnées</option>
        <option value="<?=$base_uri[0] ?>/public/login">Connexion</option>
        <option value="<?=$base_uri[0] ?>/public/user">Mon compte</option>
        <option value="<?=$base_uri[0] ?>/public/register">Créer compte</option>
       </optgroup>
    </select>
        </div>
        </section>
</main>



