<main class="mainShop">
    <h2>boutique</h2>

    <section id="shop">
        <article id="cart">
            <div class=" item1" id="item1">
                <img src="" alt="livre Roman bio Agniassou">
            </div>
            <div class=item2 id="item2">
                   <p class="paraA"><?php echo $data['Book']->getResume(); ?></p>

                <div class="item3">
                    
                    <p>Prix : <?php echo $data['Book']->getPrice() ?>€</p>
                    <small>frais de port: 7€</small>

                    <form method="POST" action="#paner">
                        <label for="quantity">Quantité :</label>
                        <input type="number" name="quantity" id="quantity" min="1" max="9" value="1">
                        <input type="submit" value="Ajouter au panier">
                    </form>
                </div>

        </article>


    </section>
    <img src="" alt="deco séparateur">----------------------</img>
    <section id="paner" class="paner">

        <form action="payment.phtml">
        <h3>Mon panier</h3>
        <table id="paner">
            <th>
                <td>livres</td>
                <td>quantité</td>
                <td>prix</td>
            </th>
            <tr>
                <td id="picture">
                    <?= $product['img']; ?>
                </td>
                <td id="resume">
                    <?= $product['resume']; ?>
                </td>
                <td id="price">
                    <?= $product['price']; ?>
                </td>
            </tr>
        </table>
        <input type="submit" name="valiateBtn" value="Valider le panier"></input>
</form>
    </section>
    <img src="" alt="deco séparateur">----------------------</img>
</main>


