<main class="mainShop">
    <h2>Boutique</h2>

    <section id="shop">
        <?php foreach ($data as $book)
       { ?>
            <article id="cart">
                <div class="item1" id="item1">
                    <img class="imgShop" src="<?php echo  $base_uri[0].'/public/assets/img/'.$book->getImg(); ?>" alt="image livre Djue Koffi">
                </div>                      
                <div class="item2" id="item2">
                    <span id="resume"><?php echo $book->getResume(); ?></span>
                    <div class="item3">
                        <p>Prix : <?php echo $book->getPrice() ?> €</p>
                        <small>Frais de port: 7€</small>
                        <form method="POST" action="">
                            <label for="quantity">Quantité :</label>
                            <input type="number" name="quantity" id="quantity" min="1" max="9" value="1">
                            <input type="submit" name="Panier" value="Ajouter au panier">
                        </form>
                    </div>
                </div>
            </article>
        <?php } ?>
    </section>
</main>

    </section>
    <img src="" alt="deco séparateur">----------------------</img>
    <section id="paner" class="paner">

        <form action="">
        <h3>Mon panier</h3>
        <table id="paner">
            <th>
                <td>livres</td>
                <td>quantité</td>
                <td>prix</td>
            </th>
            <tr>
                <td id="img">
                   
                </td>
                <td id="resume">
                    
                </td>
                <td id="price">
                   
                </td>
            </tr>
        </table>
        <input type="submit" name="valiateBtn" value="Valider le panier"></input>
</form>
    </section>
    <img src="" alt="deco séparateur">----------------------</img>
</main>


