<main class="mainUser">
             <h1>Mon compte</h1>
        <section>

            <div class="order">
                <h3>Mes Commandes passée</h3>
                <p>-</p>
                <p>-</p>
            </div>
            <div class="profil">
                <h3> Mon Profil</h3>
                <table>
                     
                         <thead>
                              <tr>
                                  <th>Nom</th>
                                  <th>Prenom</th>
                                  <th>Adresse</th>
                                  <th>E-mail</th>
                                  <th></th>
                              </tr>
                         </thead>
                         <tbody>
                          
                                 <tr>
                                     <td>krillin</td>
                                     <td>krillin</td>
                                     <td>cap nord</td>
                                     <td>krilin@mail.fr</td>
                                     <td><button>Modifier</button></td>
                                 </tr>
                                
                        </tbody>
                        
                </table>
                <span id="userProfil"></span>
                <form class="formUser" method="POST" action="<?= $base_uri[0] ?>/public/logout">
                   
                    <input type="submit" name="logout" value="déconnexion"/>
                    <input type="submit" name="deleteProfil" value="supprimer mon compte"> 
                 </form>
            </div>
        </section>
         <section>
            <div class="titleSelect">
                 <h3>Vous recherchez un élément?</h3>
                 <p>Voici un selecteur de page pour mieux vous retrouvez à tout de suite dans les prochaines pages </p>
            </div>
             <div class="select">
            <label for="selecteur"></label>
            <select id="selecteur" onchange="nextPage()">
                <optgroup label="Sélectionnez une page :">
                    <option>Sélectionnez un onglet :</option>
        <option value="<?=$base_uri[0] ?>/public/home">Accueil du site</option>
        <option value="<?=$base_uri[0] ?>/public/home">A propos de l'Auteur</option>
        <option value="<?=$base_uri[0] ?>/public/home">Photos</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Boutique</option>
        <option value="<?=$base_uri[0] ?>/public/shop">Panier</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Formulaire de Contact</option>
        <option value="<?=$base_uri[0] ?>/public/contact">Coordonnées</option>
        <option value="<?=$base_uri[0] ?>/public/login">Connexion</option>
        <option value="<?=$base_uri[0] ?>/public/user">Mon compte</option>
        <option value="<?=$base_uri[0] ?>/public/register">Créer compte</option>
       </optgroup>
    </select>
        </div>
        </section>
</main>
