<main>
        <section>

            <div class="order">
                <h3>mes Commandes passée</h3>
                <span id="order"></span>
            </div>
            <div class>
                <h3> mon Profil</h3>
                <table>
                         <thead>
                              <tr>
                                  <td>Nom</td>
                                  <td>Prenom</td>
                                  <td>Addresse</td>
                                  <td>email</td>
                              </tr>
                         </thead>
                         <tbody>
                                 <tr>
                                     <td id="name"></td>
                                     <td id="firstName"></td>
                                     <td id="address"></td>
                                     <td id="email"></td>
                                 </tr>
                        
                        
                        </tbody>
                </table>
                <span id="userProfil"></span>
                <input type="submit" name="deleteProfil" value="supprimer mon compte"> <!--deleteprofil a créé-->
            </div>
        </section></main>
