<main>
        <section>

            <div class="order">
                <h3>mes Commandes passée</h3>
                <span id="order"></span>
            </div>
            <div class>
                <h3> mon Profil</h3>
                <span id="userProfil"></span>
                <input type="submit" name="deleteProfil" value="supprimer mon compte">
            </div>
        </section></main>
